package com.sommelier.wine4you.model.product.wine;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum WineTaste {
    TROPICAL("Tropical"),
    BLACKBERRY("Blackberry"),
    CHOCOLATE("Chocolate"),
    VANILLA("Vanilla"),
    DRIED_CHERRY("Dried Cherry"),
    BLACK_CURRANT("Black Currant"),
    CHERRY("Cherry"),
    STRAWBERRY("Strawberry"),
    BLACK_FRUIT("Black Fruit"),
    SPICE("Spice"),
    RED_BERRY("Red Berry"),
    CRANBERRY("Cranberry"),
    CURRANT("Currant"),
    DARK_BERRY("Dark Berry"),
    RED_FRUIT("Red Fruit"),
    VIOLET("Violet"),
    PLUM("Plum"),
    LICORICE("Licorice"),
    BLACK_CHERRY("Black Cherry"),
    SAGE("Sage"),
    HERB("Herb"),
    BUTTER("Butter"),
    PEAR("Pear"),
    PASSIONFRUIT("Passionfruit"),
    GOOSEBERRY("Gooseberry"),
    CITRUS("Citrus"),
    APRICOT("Apricot"),
    STONE_FRUIT("Stone Fruit"),
    PEACH("Peach"),
    MELON("Melon"),
    ALMOND("Almond"),
    APPLE("Apple"),
    MANGO("Mango"),
    LIME("Lime"),
    FLORAL("Floral"),
    MINERAL("Mineral"),
    WHITE_PEACH("White Peach"),
    FIG("Fig"),
    WHITE_FRUIT("White Fruit"),
    TOAST("Toast"),
    GREEN_APPLE("Green Apple"),
    RED_CHERRY("Red Cherry"),
    BERRY("Berry"),
    FRUITY("Fruity"),
    RASPBERRY("Raspberry"),
    CASSIS("Cassis"),
    EARTH("Earth"),
    COCONUT("Coconut"),
    CINNAMON("Cinnamon"),
    PEPPER("Pepper"),
    MULBERRY("Mulberry"),
    TOBACCO("Tobacco"),
    CREAM("Cream"),
    LEMON("Lemon"),
    ANISE("Anise"),
    WHITE_FLOWER("White Flower"),
    PINEAPPLE("Pineapple"),
    BISCUIT("Biscuit"),
    GOLDEN_APPLE("Golden Apple"),
    HONEY("Honey"),
    GRAPEFRUIT("Grapefruit"),
    FLINT("Flint"),
    NUT("Nut");

    private final String taste;
}
