INSERT INTO public.wines (brand, made_in_country, in_stock, price, title, capacity, description, "name", wine_type,
                          event_id, wine_style_id, wine_taste_id,meal_id)
VALUES ('Chateau de la Chapelle', 'France', true, 250.00, 'Chateau de la Chapelle Blaye Cotes de Bordeaux, 2018', 0.75,
        'This unoaked wine is a saturated deep purple-black in colour, with ... aromas of warm blackcurrant and black cherry fruits and sweet, fresh plums. On the palate, it is ... a torrent of pure fruit, soft tannins and juicy acidity.',
        'Blaye Cotes de Bordeaux', 'RED', 2, 7, 6, 1),
       ('San Gregorio', 'Spain', true, 488.99, 'San Gregorio El Vergal Tempranillo, 2020', 0.75,
        'Plums and grapes on the nose with hints of vanilla, following through to a medium body, fresh fruit and a bright finish." A perfect food wine, or on its own.',
        'El Vergal Tempranillo', 'RED', 3, 7, 2, 2),
       ('Conde De Caralt', 'Spain', true, 512.77, 'Conde de Caralt Brut NV Cava', 1.5,
        'Grassy citrus aromas rest comfortably on a mild, nonaggressive bouquet. A citrusy mouthfeel isnt overly bubbly, while pithy lime and tangerine flavors finish mild, with tangy acidity and a cleansing quality.',
        'Brut NV Cava', 'CHAMPAGNE_SPARKLING', 3, 3, 40, 3),
       ('Mumm', 'France', true, 433.20, 'GH Mumm Grand Cordon Brut Champagne', 0.75,
        'Toast and dried fruit notes mix in this very harmonious dry Champagne, which is full of flavor- dried apricot, candied orange peel, nut and smoke- but still elegant and light-weight. The rich, toasty note lingers on the vibrant finish.',
        'Grand Cordon Brut Champagne', 'CHAMPAGNE_SPARKLING', 4, 2, 26, 4),
       ('Nicolas Feuillatte', 'France', true, 459.20, 'Nicolas Feuillatte Brut Champagne', 0.75,
        'Rich and creamy, showing the dried fruit, nut and spice notes of fruitcake, with lemon meringue, quince and honey flavors. Clean citrusy acidity integrates beautifully and provides an elegance to this refined Champagne',
        'Brut Champagne', 'CHAMPAGNE_SPARKLING', 1, 3, 37, 5),
       ('Chateau De Nages', 'France', true, 394.50, 'Chateau de Nages Bulles de Nages Extra Brut', 0.75,
        'This sparkling100% Grenache Blanc displays great finesse and amazing freshness. This elegant Extra-Brut wine benefits from lees aging for 6 months and expresses notes of white flowers, pear, and passionfruit, with a lively and lingering finish',
        'Bulles de Nages Extra Brut', 'CHAMPAGNE_SPARKLING', 2, 7, 38, 6),
       ('Marques De Monistrol', 'Spain', true, 350.12, 'Marques de Monistrol Brut Cava', 0.75,
        'An attractive and harmonious example, showcasting pretty aromas of orchid fruit. A delicate autolytic character, and flavours of fresh bread and toasted brioche add an appeling complexity on the palete',
        'Brut Cava', 'CHAMPAGNE_SPARKLING', 2, 9, 23, 6),
       ('Tesoro della Regina', 'Italy', true, 450.00, 'Tesoro della Regina Rose', 0.75,
        'You''ll be transported to the Italian Riviera. Refreshing and light as a summer breeze. Goes well with a crisp Caesar salad, a platter of grilled veggies and friends.',
        'Rose', 'ROSE', 2, 11, 42, 5),
       ('Domaine Loubejac', 'USA', true, 734.22, 'Domaine Loubejac Pinot Noir Willamette Valley, 2020', 0.75,
        'Lots of hibiscus with dried strawberry on the nose and palate. Medium body, firm tannins and a lightly chewy yet polished and fine finish. Drinkable now.',
        'Pinot Noir', 'RED', 3, 7, 18, 4),
       ('Olema', 'USA', true, 240.34, 'Olema Cabernet Sauvignon Sonoma County, 2019', 0.75,
        'A lot of chocolate, coconut and vanilla on the nose with some ripe dark fruit. Some tobacco, too. Medium-bodied, firm and fruity. Delicious now.',
        'Cabernet Sauvignon', 'RED', 4, 8, 2, 3);
INSERT INTO public.wines (brand, made_in_country, in_stock, price, title, capacity, description, "name", wine_type,
                          event_id, wine_style_id, wine_taste_id, meal_id)
VALUES ('Quinta das Carvalhas', 'Portugal', true, 820.40, 'Quinta das Carvalhas Touriga Nacional Douro, 2017', 0.75,
        'A rich and smooth wine, this has both power and density. Its perfumed character is still prominent and full of potential. The wine''s structure and texture will see it mature from next year.',
        'Touriga Nacional Douro', 'RED', 2, 6, 3, 2),
       ('Marchese Dell''elsa', 'Italy', true, 854.73, 'Marchese dell''Elsa Moscato d''Asti', 0.75,
        'Asti, Piedmont, Italy - A fruit-driven people pleaser. to pair with a fruit plate. Or sip on the porch after dinner.',
        'Moscato D''asti', 'CHAMPAGNE_SPARKLING', 1, 5, 28, 1),
       ('La Vostra', 'Italy', true, 920.23, 'La Vostra Prosecco Rose', 0.75,
        'Beverage Dynamics-Italy - "Slight cherry zesty character give this wine structure and fun."', 'Prosecco Rose',
        'CHAMPAGNE_SPARKLING', 4, 11, 8, 1),
       ('Uro', 'Spain', true, 488.02, 'Uro Toro La Enfermera Tempranillo, 2020', 0.75,
        'James Suckling-Toro, Spain - "Aromas of smoke, It''s a bigger wine, but the tannins show focus and softness. 100% tinta de toro."',
        'Toro La Enfermera Tempranillo', 'RED', 3, 7, 9, 2),
       ('Louis Bouillot', 'France', true, 772.83, 'Louis Bouillot Perle de Vigne Brut', 0.375,
        'Wine & Spirits-Burgundy, France - This is a blend focused and clean. The bubbles are ready to take on any raw shellfish.',
        'Perle De Vigne', 'CHAMPAGNE_SPARKLING', 1, 7, 31, 3),
       ('Ed Edmundo', 'Argentina', true, 710.23, 'Ed Edmundo Cabernet Sauvignon, 2021', 0.75,
        'jJames Suckling-Mendoza, Argentina - "Savory sweet tobacco, blackcurrants and some thyme tightly before a long, savory finish."',
        'Cabernet Sauvignon', 'RED', 2, 7, 5, 4),
       ('Meleto', 'Italy', false, 1310.77, 'Castello Meleto Borgaio Rosso di Toscana, 2019', 0.75,
        'James Suckling-Toscana IGT, Tuscany, Italy - "A fruity red with plenty of dried-berry, walnut courses and grilled red meats and cheeses.',
        'Borgaio Rosso Di Toscana', 'RED', 4, 7, 11, 5),
       ('Pietramerana', 'Italy', true, 622.74, 'Pietramerana Sangiovese Toscana IGT, 2019', 0.75,
        'James Suckling-Italy - Tuscany - Toscana - too. Medium-bodied with fine, firm tannins. Fragrant and spicy finish. "',
        'Sangiovese Toscana Igt', 'RED', 3, 6, 7, 6),
       ('Altaland', 'Argentina', true, 219.99, 'Altaland Malbec Mendoza, 2020', 0.75,
        'James Suckling-Italy - Tuscany - Toscana - too. Medium-bodied with fine, firm tannins. Fragrant and spicy finish. "',
        'Malbec Mendoza', 'RED', 1, 7, 14, 1),
       ('Albino Armani', 'Italy', true, 902.37, 'Armani Prosecco', 0.75,
        'Asti, Piedmont, Italy - A fruit-driven people pleaser. to pair with a fruit plate. Or sip on the porch after dinner.',
        'Prosecco', 'CHAMPAGNE_SPARKLING', 3, 7, 26, 2);
INSERT INTO public.wines (brand, made_in_country, in_stock, price, title, capacity, description, "name", wine_type,
                          event_id, wine_style_id, wine_taste_id, meal_id)
VALUES ('Cruse', 'France', true, 312.93, 'Cruse Brut', 0.75,
        'Asti, Piedmont, Italy - A fruit-driven people pleaser. to pair with a fruit plate. Or sip on the porch after dinner.',
        'Brut', 'CHAMPAGNE_SPARKLING', 2, 3, 31, 3),
       ('Famille Bougrier', 'France', true, 480.00, 'Bougrier Rose d''Anjou, 2021', 1.5,
        'Light, pinky hue. Rose water, nectarines and light cherries on the nose, followed by an off-dry palate with fresh acidity. Simple and light, but easy to appreciate.',
        'Rose d''Anjou', 'ROSE', 2, 12, 8, 4),
       ('Almaden', 'USA', true, 850.00, 'Almaden White Zinfandel', 5.0,
        'A refreshing crisp blush wine with delicate strawberry aromas. A very fresh, drinkable wine with a pleasing, non-bitter finish.',
        'White Zinfandel', 'ROSE', 2, 11, 8, 5),
       ('Mathilde Chapoutier Selection', 'France', true, 330.00, 'Mathilde Chapoutier Grand Ferrage Provence Rose',
        0.75, 'A refreshing crisp blush wine with delicate strawberry aromas.', 'Grand Ferrage Provence Rose', 'ROSE',
        4, 12, 38, 6),
       ('Turley', 'USA', true, 860.00, 'Turley Zinfandel Steacy Ranch , 2017', 0.75,
        'Steacy Ranch was one of the first vineyards planted on St. George rootstock in Lodi, which has since become the gold standard for Zinfandel in California. This wine exhibits lovely aromas and flavors of cassis, cherries, berries and plums.',
        'Zinfandel Steacy Ranch', 'ROSE', 1, 6, 17, 6),
       ('Buttercream', 'USA', false, 740.00, 'Buttercream Chardonnay', 0.75,
        'Big and buttery. Decadent and excellent with scallops, bacon, cream. Same story with grilled salmon. Sip on the dock, the backyard, the front porch. Bliss. Vegan',
        'Chardonnay', 'WHITE', 4, 1, 22, 5),
       ('Giant Sky', 'New Zealand', true, 500.00, 'Giant Sky Marlborough Sauv Blanc', 0.75,
        'This light-bodied wine is fresh and crisp, full of intense flavors of gooseberry and passionfruit complimented by capsicum and a hint of melon. Enjoy with fresh seafood and antipasto!',
        'Marlborough Sauv Blanc', 'WHITE', 3, 9, 24, 4),
       ('Anne de K', 'France', true, 650.00, 'Anne de K Pinot Gris', 0.75,
        'Typical nose, expressive with apricot and mirabelle with a subtle note of smoke. A mouth with a beautiful structure. It can be served as aperitif or completes perfectly with salads and white meats like poultry and veal.',
        'Pinot Gris', 'WHITE', 1, 7, 27, 3),
       ('Domaine Vivonne', 'France', true, 550.00, 'Domaine de La Vivonne Cotes de Provence Rose, 2021', 0.75,
        'A deliciously fruity wine, this is packed with red currant flavors that lie on a pure line of bright acidity. It is light in alcohol while strong in flavor and intensity',
        'Cotes de Provence Rose', 'ROSE', 2, 11, 8, 2),
       ('Olema', 'France', true, 550.00, 'Olema Rose Cotes De Provence, 2021', 0.75,
        'Some cherry, crushed stone and slate aromas with hints of roses and white pepper follow through to a medium body. Creamy structure with phenolics and framing. Mostly grenache with some cinsault, syrah and carignan. Drink now.',
        'Rose Cotes De Provence', 'ROSE', 4, 11, 8, 1);
INSERT INTO public.wines (brand, made_in_country, in_stock, price, title, capacity, description, "name", wine_type,
                          event_id, wine_style_id, wine_taste_id, meal_id)
VALUES ('Stella Rosa', 'Italy', true, 888.50, 'Stella Rosa Rose', 1.5,
        'The perfect hint of sweetness and an equal balance of grace, beauty, and peace qualities you''ll immediately discover within yourself. The wine is combined with all-natural flavors of an off-dry Rose, bursting with berry flavors. Serve chilled by-the-glass',
        'Rose', 'ROSE', 2, 12, 35, 1),
       ('Maison', 'France', true, 560.00, 'Maison No. 9 Rose by Post Malone', 0.75,
        'Crispy, refreshing, and smooth. This dry, classic Rose is wonderfully balanced and round with a texture that is mouthwatering and savory. Dominant orchard fruits make up the bouquet, such as peaches.',
        'No. 9 Rose', 'ROSE', 1, 12, 8, 2),
       ('Chateau Miraval', 'France', true, 340.00, 'Chateau Miraval Cotes de Provence Rose, 2021', 0.75,
        'This is an impressive rose, elegant with finely balanced fruit and texture. Citrus and raspberries shine through a taut structure. The aftertaste is crisp and fresh.',
        'Cotes de Provence Rose', 'ROSE', 4, 11, 8, 3),
       ('Angeline', 'USA', true, 520.00, 'Angeline Sauvignon Blanc Reserve, 2020', 0.75,
        'Dried pineapple, lemon, pear, cardamom, flint and blanched almond on the nose. It''s a medium to full-bodied with bright acidity. Mineral and subtly spicy',
        'Sauvignon Blanc Reserve', 'WHITE', 2, 9, 26, 4),
       ('Winzer Krems', 'Austria', true, 580.00, 'Winzer Krems Riesling Kreuzberg Reserve, 2019', 0.75,
        'A subtle sense of fresh lemon zest is tentative on the shy nose. The palate adds a pithier note and gives this a real zesty core. This seems light but is anchored in stone and plenty of citric depth',
        'Riesling Kreuzberg Reserve', 'WHITE', 3, 5, 32, 5),
       ('Saladini Pilastri', 'Italy', true, 490.00, 'Saladini Pilastri Falerio, 2021', 0.75,
        'Intense ripe fruit, melon, peach, pear, citrus and mineral notes. Interesting multi-grape blend. Easy drinking and good value for money!',
        'Falerio', 'WHITE', 4, 7, 29, 6),
       ('Dr Heidemanns-Bergweiler', 'Germany', true, 390.00, 'Dr Heidemanns Riesling QbA', 0.75,
        'Apple and peach flavors infuse this crisp and refreshing Riesling from Dr. Heidemanns, world renowned as one of the finest estates in the Mosel. With flavors that are light and lingering, enjoy as an aperitif paired with spicy shrimp stir-fry.',
        'Riesling QbA', 'WHITE', 2, 10, 32, 1),
       ('Donnachiara', 'Italy', true, 790.00, 'Donnachiara Fiano di Avellino Empatia, 2020', 0.75,
        'Peaches, apricots, blanched almonds, honeysuckle, lemon curd and some custard on the nose. Medium-bodied with bright, tangy acidity. Long, focused, spicy and delicious.',
        'Fiano di Avellino Empatia', 'WHITE', 2, 11, 33, 2),
       ('Domaine Chatelain', 'France', true, 890.00, 'Domaine Chatelain Petit Chablis', 0.75,
        'This fresh, invigorating unoaked Chardonnay from the northern reaches of Burgundy is filled with lemon and flint notes, with hints of apple and pear. Citrus and mineral dominate on the nose. Try this great value with fresh seafood or light poultry dishes.',
        'Petit Chablis', 'WHITE', 4, 9, 32, 3),
       ('Dr Heidemanns-Bergweiler', 'Germany', true, 480.00, 'Dr Heidemanns Bernkastel Badstube Riesling Spatlese',
        0.75,
        'Boasting apricot, vanilla cream and citrus flavors, this Spatlese is delicate and harmonious with fruitiness balanced by acidity and a touch of minerality. It comes from the town of Bernkastel and goes well with spicy dishes.',
        'Bernkastel Badstube Riesling Spatlese', 'WHITE', 1, 10, 27, 4);
